data:
    type: "LLdataset"
    train_dataset: "LOLv1"
    val_dataset: "LOLv1eval"
    patch_size: 128
    channels: 3
    num_workers: 1
    data_dir: "./data/Image_restoration/LSRW_dataset"
    ckpt_dir: "./ckpt"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    num_sampling_timesteps: 20

training:
    batch_size: 1
    n_epochs: 2000
    validation_freq: 2000

sampling:
    batch_size: 1

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001